version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  backend:
    image: express-backend-ex:v1
    restart: always
    build:
      context: .
    ports:
      - 18888:18888
    depends_on:
      - mongo
