version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 22222:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo

  backend:
    image: node:16.3.0-alpine3.13
    restart: always
    volumes:
      - $PWD:/app
    ports:
      - 18888:18888
    depends_on:
      - mongo
    working_dir: /app/dist
    entrypoint:
      - node
      - main.js
